### ISSUE TITLE
Add a previous and next button to discussions.

### ISSUE THREAD

**Issue by DoperBeats** [askvortsov1/flarum-article-series#1]
Currently, the fastest way to move to the next discussion is by scrolling to the top of the page and click on the next one in the list. Instead it would be nice to have a next button to click at the bottom of the discussion to move to the next one.

![image](https://user-images.githubusercontent.com/65038941/132440025-7a5d504c-d8d3-4782-bf25-dd099e8fede8.png)

Next to the reply/like or somewhere around it would be nice.

**Comment by askvortsov1** [comment]
Fixed in ac5552784579f5b04fe0c80f5d254b6e5c613519
