### ISSUE TITLE
Article settings not visible unless blog disabled..

### ISSUE THREAD

**Issue by eddiewebb** [askvortsov1/flarum-article-series#2]
I must be doing something dumb because right now the only way I can define article series settings for an individual posts is to disable Blog's discussion/tag url rewriting, go to discussion view (non blog) of post, and use discussion drop down.  The drop-down shown for blogs does not include it. But if I leave it in that state none of the article setting features are visible to users...

<img width="626" alt="Screen Shot 2021-12-31 at 9 51 15 AM" src="https://user-images.githubusercontent.com/5262154/147829147-f62d6fb9-e21a-4f2b-a7c0-39c0743a5a84.png">

**Comment by askvortsov1** [comment]
> I must be doing something dumb because right now the only way I can define article series settings for an individual posts is to disable Blog's discussion/tag url rewriting, go to discussion view (non blog) of post, and use discussion drop down.  The drop-down shown for blogs does not include it. But if I leave it in that state none of the article setting features are visible to users...
> 
> <img width="626" alt="Screen Shot 2021-12-31 at 9 51 15 AM" src="https://user-images.githubusercontent.com/5262154/147829147-f62d6fb9-e21a-4f2b-a7c0-39c0743a5a84.png">
> 
> 

Unfortunately this one is currently the case, I've been editing these settings by accessing the discussions through the discussion list too as a workaround. You can access it via the triple dots so you don't need to disable blog.

I need to look into sending a PR to blog so that they extend the discussion controls instead of creating their own.

**Comment by eddiewebb** [comment]
Makes sense on the reason. Thanks for work around, List approach works way better than the disable dance, lol. 🩰

**Comment by askvortsov1** [comment]
Fixed in https://github.com/askvortsov1/flarum-article-series/commit/065678d03230b71261041fa09067af8120f040ed
