### ISSUE TITLE
When I install this extension, it says:

### ISSUE THREAD

**Issue by ash3T** [askvortsov1/flarum-article-series#5]
composer require askvortsov/flarum-article-series    
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^0.1.2 for askvortsov/flarum-article-series
./composer.json has been updated
Running composer update askvortsov/flarum-article-series
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires askvortsov/flarum-article-series ^0.1.2 -> satisfiable by askvortsov/flarum-article-series[v0.1.2].
    - askvortsov/flarum-article-series v0.1.2 requires v17development/flarum-blog ^0.4.0 -> found v17development/flarum-blog[v0.4.0, 0.4.1, 0.4.2] but it conflicts with your root composer.json require (^0.6.4).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require askvortsov/flarum-article-series:*" to figure out if any version is installable, or "composer require askvortsov/flarum-article-series:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Sorry, I did not know how to add a new pull requests, so I submit a new issue here.

I believe other people has encounter the same issue when they try to install this extension.

You can take a look at https://discuss.flarum.org/d/28849-article-series-for-flarum-blog

Thanks.

**Comment by askvortsov1** [comment]
I updated this a long time ago, but in my infinite wisdom, forgot to publish a new release. Sorry about that! Should be done now
